# Generated by Django 4.0.4 on 2022-07-17 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_order_name_alter_order_order_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.TextField(verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(verbose_name='Ціна замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_text',
            field=models.TextField(verbose_name='Текст замовлення'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.TextField(verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500, verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(default='+380', max_length=20, verbose_name='Номер телефону'),
        ),
    ]
