# Generated by Django 4.0.4 on 2022-07-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_order_created_alter_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(blank=True, max_length=20, verbose_name='Номер телефону'),
        ),
    ]
