# Generated by Django 4.0.4 on 2022-07-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, max_length=500, verbose_name='Додаткова інформація'),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Адреса'),
        ),
    ]
