# Generated by Django 4.0.4 on 2022-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/dish'),
        ),
        migrations.AddField(
            model_name='dishtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/dishtype'),
        ),
    ]
